# Generated by Django 5.1.3 on 2024-11-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='tag',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
