# Generated by Django 5.1.3 on 2024-11-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasks_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='data_complete',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
