# Generated by Django 5.1.3 on 2024-11-17 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_tasks_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='tag',
        ),
    ]
