# Generated by Django 5.1.3 on 2024-11-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_tasks_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='data_add',
            field=models.DateField(blank=True, null=True),
        ),
    ]
