# Generated by Django 5.1.3 on 2024-11-18 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_tasks_data_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='data_add',
            field=models.DateField(blank=True, default=datetime.date(2024, 11, 18)),
        ),
    ]
