# Generated by Django 5.1.3 on 2024-11-21 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_tasks_data_add_alter_tasks_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='subtask_four',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='subtask_one',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='subtask_three',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='subtask_two',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='data_add',
            field=models.DateField(blank=True, default=datetime.date(2024, 11, 21)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
