# Generated by Django 5.1.3 on 2024-11-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_tasks_subtask_four_tasks_subtask_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='subtask_four',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='subtask_one',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='subtask_three',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='subtask_two',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
