# Generated by Django 5.1.3 on 2024-12-11 13:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_tasks_subtask_four_alter_tasks_subtask_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='data_add',
            field=models.DateField(blank=True, default=datetime.date(2024, 12, 11)),
        ),
        migrations.CreateModel(
            name='Subtasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='tasks.tasks')),
                ('sub_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main', to='tasks.tasks')),
            ],
        ),
    ]
