# Generated by Django 5.1.3 on 2024-12-15 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_tasks_data_add_subtasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='data_add',
            field=models.DateField(blank=True, default=datetime.date(2024, 12, 15)),
        ),
        migrations.DeleteModel(
            name='Subtasks',
        ),
    ]
